import type {
  StatusResult,
  LogEntry,
  BranchInfo,
  RemoteInfo,
  RemoteProperties,
  StashEntry,
  TagInfo,
  SubmoduleInfo,
  DiffResult,
  FileStatus,
  DiffHunk,
  DiffLine,
  WorktreeInfo,
  ReflogEntry,
  CommitFile,
  BlameLine,
  BlameResult,
  GitConfigEntry,
  DirNode,
  RecyclableCommit,
  LfsLock,
  BidirectionalBlameResult,
} from '../../electron/types/git-api';
import type {
  GithubUser,
  GithubRepository,
  GithubPullRequest,
} from '../../electron/types/github-api';
import type { AppSettings, RepositoryEntry, RepositoryMetadata } from '../../electron/types/settings-api';

export type {
  StatusResult,
  LogEntry,
  BranchInfo,
  RemoteInfo,
  RemoteProperties,
  StashEntry,
  TagInfo,
  SubmoduleInfo,
  DiffResult,
  FileStatus,
  DiffHunk,
  DiffLine,
  WorktreeInfo,
  ReflogEntry,
  CommitFile,
  BlameLine,
  BlameResult,
  GitConfigEntry,
  DirNode,
  RecyclableCommit,
  LfsLock,
  BidirectionalBlameResult,
  GithubUser,
  GithubRepository,
  GithubPullRequest,
  AppSettings,
  RepositoryEntry,
  RepositoryMetadata,
};

export const api = window.smartgit;
