/**
 * Resolution of bundled icon assets for runtime use (window icons, About logo).
 *
 * Dev:      <repo>/build/<name>          (generated by scripts/make-icons.py)
 * Packaged: <resources>/<name>           (copied via electron-builder extraResources)
 */

import { app } from 'electron';
import * as path from 'path';

export function resolveResourceIcon(name: string): string {
  if (app && app.isPackaged) {
    return path.join(process.resourcesPath, name);
  }
  return path.join(__dirname, '..', 'build', name);
}
