import { useState, useEffect, useCallback } from 'react';
import { AlertTriangle, Copy, Check, RefreshCw, ExternalLink, X, ChevronDown, ChevronRight, Trash } from './icons';
import { useToastActions } from '../stores/toastStore';
import { useI18n } from '../lib/i18n';
import { useEscapeKey } from '../hooks/useEscapeKey';
import { cn } from '../lib/utils';

/**
 * One captured error record. Stored both in-memory (for the currently
 * visible dialog) AND in localStorage (so the most recent error survives
 * a reload — if the user reloads after a white-screen crash, the dialog
 * re-opens with the previous error so they can copy the trace).
 */
export interface CapturedError {
  /** Unique id (timestamp + random suffix). */
  id: string;
  /** When the error occurred (epoch ms). */
  timestamp: number;
  /** 'render' = React render error (caught by Error Boundary). */
  /** 'uncaught' = window.onerror (sync throw). */
  /** 'unhandledrejection' = unhandled promise rejection. */
  /** 'watchdog' = the heartbeat watchdog fired (UI frozen). */
  kind: 'render' | 'uncaught' | 'unhandledrejection' | 'watchdog';
  /** Short headline shown in the dialog title bar. */
  message: string;
  /** The full Error.stack (or String(reason) when no Error). */
  stack: string;
  /** Optional componentStack from React's error boundary. */
  componentStack?: string;
  /** Where in the user's flow the error happened (best-effort). */
  context?: string;
  /** App version + git commit hash (so the dev knows which build). */
  appVersion?: string;
  /** User agent / Electron version. */
  userAgent?: string;
  /** Currently open repo path (if any). */
  repoPath?: string;
}

const STORAGE_KEY = 'prismgit-last-error';

/**
 * Persist the most recent error to localStorage so it survives a reload.
 * If the user reloads after a white-screen crash, the dialog re-opens
 * automatically on next mount with the previous error.
 */
export function persistError(err: CapturedError): void {
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(err));
  } catch {
    /* localStorage unavailable or quota exceeded — ignore */
  }
}

/** Read the persisted error (or null if none). Caller is responsible for
 *  clearing it via clearPersistedError() once the user has acknowledged it. */
export function loadPersistedError(): CapturedError | null {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) return null;
    const parsed = JSON.parse(raw);
    if (parsed && typeof parsed === 'object' && parsed.id && parsed.stack) {
      return parsed as CapturedError;
    }
  } catch {
    /* corrupt JSON — ignore */
  }
  return null;
}

/** Remove the persisted error. Called when the user dismisses the dialog. */
export function clearPersistedError(): void {
  try { localStorage.removeItem(STORAGE_KEY); } catch { /* ignore */ }
}

/**
 * Build a plain-text report the user can copy and paste into a bug report
 * or a chat message to the developer. Includes:
 *   - App version + git commit
 *   - Timestamp + error kind
 *   - Headline message
 *   - Full stack trace
 *   - Component stack (if React render error)
 *   - User agent / Electron version
 *   - Currently open repo path (if any — never includes file contents)
 */
export function buildErrorReport(err: CapturedError): string {
  const lines: string[] = [];
  lines.push('PrismGit Error Report');
  lines.push('=====================');
  lines.push('');
  lines.push(`Timestamp: ${new Date(err.timestamp).toISOString()}`);
  lines.push(`Kind: ${err.kind}`);
  if (err.appVersion) lines.push(`App version: ${err.appVersion}`);
  if (err.userAgent) lines.push(`User agent: ${err.userAgent}`);
  if (err.repoPath) lines.push(`Repository: ${err.repoPath}`);
  if (err.context) lines.push(`Context: ${err.context}`);
  lines.push('');
  lines.push('Message:');
  lines.push(err.message || '(no message)');
  lines.push('');
  lines.push('Stack trace:');
  lines.push(err.stack || '(no stack)');
  if (err.componentStack) {
    lines.push('');
    lines.push('Component stack:');
    lines.push(err.componentStack);
  }
  lines.push('');
  lines.push('— Generated by PrismGit Error Report');
  return lines.join('\n');
}

interface ErrorReportDialogProps {
  error: CapturedError | null;
  onClose: () => void;
  /** Called when the user clicks "Reload app". Default: window.location.reload(). */
  onReload?: () => void;
}

/**
 * Full-screen modal that shows a captured error with:
 *   - A short headline ("Render error" / "Unhandled rejection" / ...)
 *   - The full stack trace in a scrollable <pre>
 *   - Copy-to-clipboard button (so the user can paste it to the developer)
 *   - "Reload app" button (the most common recovery action)
 *   - "Dismiss" button (close without reloading — for non-fatal errors)
 *   - "Clear error log" button (removes the persisted error so the dialog
 *     doesn't re-appear on next reload)
 *
 * The dialog is rendered OUTSIDE the error boundary so it can show even
 * when the rest of the app has crashed. It's mounted at the App root
 * (above the Error Boundary) so a render error in any child still
 * surfaces here.
 */
export function ErrorReportDialog({ error, onClose, onReload }: ErrorReportDialogProps) {
  const { t } = useI18n();
  const toast = useToastActions();
  const [copied, setCopied] = useState(false);
  const [showFullStack, setShowFullStack] = useState(true);
  const [showComponentStack, setShowComponentStack] = useState(false);

  useEscapeKey(!!error, onClose);

  // Reset internal state when the error changes (so the dialog feels fresh
  // for each new error rather than carrying over collapsed sections).
  useEffect(() => {
    setCopied(false);
    setShowFullStack(true);
    setShowComponentStack(false);
  }, [error?.id]);

  const handleCopy = useCallback(async () => {
    if (!error) return;
    const report = buildErrorReport(error);
    try {
      await navigator.clipboard.writeText(report);
      setCopied(true);
      toast.success(t('errors.copiedToClipboard', { defaultValue: 'Error report copied to clipboard' }));
      setTimeout(() => setCopied(false), 2000);
    } catch (e) {
      // clipboard API can fail in non-secure contexts — fall back to a
      // hidden textarea + document.execCommand('copy').
      try {
        const ta = document.createElement('textarea');
        ta.value = report;
        ta.style.position = 'fixed';
        ta.style.left = '-9999px';
        document.body.appendChild(ta);
        ta.focus();
        ta.select();
        document.execCommand('copy');
        document.body.removeChild(ta);
        setCopied(true);
        toast.success(t('errors.copiedToClipboard', { defaultValue: 'Error report copied to clipboard' }));
        setTimeout(() => setCopied(false), 2000);
      } catch {
        toast.error(t('errors.copyFailed', { defaultValue: 'Failed to copy error report' }), String(e));
      }
    }
  }, [error, toast, t]);

  const handleReload = useCallback(() => {
    clearPersistedError();
    if (onReload) onReload();
    else window.location.reload();
  }, [onReload]);

  const handleDismiss = useCallback(() => {
    clearPersistedError();
    onClose();
  }, [onClose]);

  if (!error) return null;

  const report = buildErrorReport(error);
  const kindLabel = (() => {
    switch (error.kind) {
      case 'render': return t('errors.kindRender', { defaultValue: 'Render error' });
      case 'uncaught': return t('errors.kindUncaught', { defaultValue: 'Uncaught error' });
      case 'unhandledrejection': return t('errors.kindUnhandledRejection', { defaultValue: 'Unhandled promise rejection' });
      case 'watchdog': return t('errors.kindWatchdog', { defaultValue: 'UI frozen (watchdog)' });
      default: return t('errors.kindUnknown', { defaultValue: 'Error' });
    }
  })();

  return (
    <div
      className="fixed inset-0 bg-black/70 flex items-center justify-center z-[10000] animate-fade-in p-4"
      role="alertdialog"
      aria-modal="true"
      aria-labelledby="error-dialog-title"
    >
      <div
        className="panel w-full max-w-3xl max-h-[90vh] flex flex-col shadow-2xl"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-start gap-3 px-4 py-3 border-b border-border-default bg-status-deleted/10">
          <AlertTriangle size={18} className="text-status-deleted flex-shrink-0 mt-0.5" />
          <div className="flex-1 min-w-0">
            <div id="error-dialog-title" className="text-base font-medium text-text-primary">
              {kindLabel}
            </div>
            <div className="text-xs text-text-secondary mt-0.5 truncate">
              {error.message}
            </div>
          </div>
          <button
            className="icon-btn !w-7 !h-7 flex-shrink-0"
            title={t('common.close', { defaultValue: 'Close' })}
            onClick={handleDismiss}
          >
            <X size={14} />
          </button>
        </div>

        {/* Body */}
        <div className="flex-1 overflow-y-auto p-4 space-y-3">
          {/* Meta info */}
          <div className="text-2xs text-text-tertiary grid grid-cols-2 gap-x-4 gap-y-0.5 font-mono">
            <span>Timestamp:</span>
            <span>{new Date(error.timestamp).toLocaleString()}</span>
            {error.appVersion && (<><span>App version:</span><span>{error.appVersion}</span></>)}
            {error.repoPath && (<><span>Repository:</span><span className="truncate">{error.repoPath}</span></>)}
            {error.context && (<><span>Context:</span><span className="truncate">{error.context}</span></>)}
          </div>

          {/* Stack trace (collapsible) */}
          <div>
            <button
              className="flex items-center gap-1 text-xs font-semibold text-text-secondary hover:text-text-primary mb-1"
              onClick={() => setShowFullStack(!showFullStack)}
            >
              {showFullStack ? <ChevronDown size={11} /> : <ChevronRight size={11} />}
              {t('errors.stackTrace', { defaultValue: 'Stack trace' })}
            </button>
            {showFullStack && (
              <pre
                className="text-xs font-mono whitespace-pre-wrap break-all bg-bg-tertiary border border-border-default rounded p-3 max-h-64 overflow-y-auto text-text-primary"
                data-testid="error-stack-trace"
              >
                {error.stack || t('errors.noStackAvailable', { defaultValue: '(no stack trace available)' })}
              </pre>
            )}
          </div>

          {/* Component stack (only for React render errors) */}
          {error.componentStack && (
            <div>
              <button
                className="flex items-center gap-1 text-xs font-semibold text-text-secondary hover:text-text-primary mb-1"
                onClick={() => setShowComponentStack(!showComponentStack)}
              >
                {showComponentStack ? <ChevronDown size={11} /> : <ChevronRight size={11} />}
                {t('errors.componentStack', { defaultValue: 'Component stack' })}
              </button>
              {showComponentStack && (
                <pre className="text-xs font-mono whitespace-pre-wrap break-all bg-bg-tertiary border border-border-default rounded p-3 max-h-48 overflow-y-auto text-text-secondary">
                  {error.componentStack}
                </pre>
              )}
            </div>
          )}

          {/* Plain-text report preview (so the user sees what they'd be sending) */}
          <details className="text-xs">
            <summary className="cursor-pointer text-text-secondary hover:text-text-primary font-semibold">
              {t('errors.fullReportPreview', { defaultValue: 'Full report preview (what gets copied)' })}
            </summary>
            <pre className="mt-2 text-xs font-mono whitespace-pre-wrap break-all bg-bg-tertiary border border-border-default rounded p-3 max-h-48 overflow-y-auto text-text-tertiary">
              {report}
            </pre>
          </details>

          {/* Hint text */}
          <div className="text-xs text-text-tertiary bg-bg-tertiary border border-border-subtle rounded p-2">
            {t('errors.hint', {
              defaultValue: 'An unexpected error occurred. Please copy the report above and send it to the developer — it includes the stack trace and app version needed to diagnose the issue. Click "Reload app" to restart.'
            })}
          </div>
        </div>

        {/* Footer */}
        <div className="flex items-center justify-between gap-2 px-4 py-3 border-t border-border-default bg-bg-secondary">
          <button
            className="btn btn-secondary text-xs"
            title={t('errors.clearErrorLog', { defaultValue: 'Clear the persisted error so the dialog doesn\'t re-appear on next reload' })}
            onClick={() => { clearPersistedError(); toast.info(t('errors.errorLogCleared', { defaultValue: 'Error log cleared' })); }}
          >
            <Trash size={11} />
            {t('errors.clearLog', { defaultValue: 'Clear log' })}
          </button>
          <div className="flex items-center gap-2">
            <button
              className="btn btn-secondary text-xs"
              onClick={handleDismiss}
            >
              {t('common.dismiss', { defaultValue: 'Dismiss' })}
            </button>
            <button
              className={cn('btn text-xs', copied ? 'btn-secondary' : 'btn-primary')}
              onClick={handleCopy}
              title={t('errors.copyTooltip', { defaultValue: 'Copy the full error report (with stack trace) to the clipboard' })}
            >
              {copied ? <Check size={11} /> : <Copy size={11} />}
              {copied
                ? t('errors.copied', { defaultValue: 'Copied!' })
                : t('errors.copyReport', { defaultValue: 'Copy report' })}
            </button>
            <button
              className="btn btn-primary text-xs"
              onClick={handleReload}
              title={t('errors.reloadTooltip', { defaultValue: 'Reload the app (most errors are recoverable with a reload)' })}
            >
              <RefreshCw size={11} />
              {t('errors.reloadApp', { defaultValue: 'Reload app' })}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

/**
 * Helper: format an unknown value (Error, string, object) into a stack trace
 * string. Used by the global error handlers + the React error boundary.
 */
export function formatErrorStack(reason: unknown): { message: string; stack: string } {
  if (reason instanceof Error) {
    return {
      message: reason.message || reason.name,
      stack: reason.stack || `(no stack — ${reason.name}: ${reason.message})`,
    };
  }
  if (typeof reason === 'string') {
    return { message: reason, stack: reason };
  }
  if (reason && typeof reason === 'object') {
    try {
      const str = JSON.stringify(reason, null, 2);
      const msg = (reason as { message?: string }).message || String(reason);
      return { message: msg, stack: str };
    } catch {
      return { message: String(reason), stack: String(reason) };
    }
  }
  return { message: String(reason), stack: String(reason) };
}

/**
 * Helper: collect app version + user agent + repo path for the report.
 * Reads from localStorage (where settings live) and navigator — never
 * includes file contents or git data.
 */
export function collectEnvironment(): { appVersion?: string; userAgent?: string; repoPath?: string } {
  const env: { appVersion?: string; userAgent?: string; repoPath?: string } = {};
  try {
    // App version — Vite injects this at build time.
    env.appVersion = (typeof __APP_VERSION__ !== 'undefined' ? __APP_VERSION__ : undefined)
      || (typeof process !== 'undefined' && process.env?.npm_package_version)
      || undefined;
  } catch { /* ignore */ }
  try {
    env.userAgent = typeof navigator !== 'undefined' ? navigator.userAgent : undefined;
  } catch { /* ignore */ }
  try {
    // Repo path is stored in localStorage by repositoryStore when a repo opens.
    // We DON'T read it from the store directly because the store might be
    // in a broken state when an error is captured.
    const raw = localStorage.getItem('prismgit-current-repo');
    if (raw) env.repoPath = raw;
  } catch { /* ignore */ }
  return env;
}

// Allow the build to define __APP_VERSION__ without breaking TypeScript.
declare const __APP_VERSION__: string | undefined;
