/**
 * LAR-3 — AI Assistant chat i18n strings.
 *
 * Used by:
 *   - src/components/AiAssistant.tsx (floating popup)
 *   - src/pages/AiChatPage.tsx (full-page chat)
 *
 * Both surfaces share the same keys so the user gets the same translations
 * regardless of where they interact with the AI.
 */

export const en: Record<string, string> = {
  // ── Header / titles ──────────────────────────────────────────────────────
  'aiAssistant.title': 'AI Assistant',
  'aiAssistant.toggleTitle': 'Toggle AI Assistant chat (Ctrl+Shift+A)',
  'aiAssistant.disabledHint': 'Enable AI in Settings → AI first',
  'aiAssistant.clearHistory': 'Clear chat history',
  'aiAssistant.clearChat': 'Clear chat',
  'aiAssistant.exportChatLog': 'Export chat log as Markdown (for debugging / sharing)',
  'aiAssistant.exportChatLabel': 'Export chat log',
  'aiAssistant.stopGeneration': 'Stop generation',
  'aiAssistant.stopButton': 'Stop',
  'aiAssistant.switchProvider': 'Switch AI Provider',
  'aiAssistant.switchProviderHint': 'Switching preserves the conversation — the new provider continues the chat.',
  'aiAssistant.noProviderSelected': 'no provider',
  'aiAssistant.providerTitle': 'Provider',

  // ── Empty / loading states ───────────────────────────────────────────────
  'aiAssistant.emptyHint': 'Ask anything about this repository — "what changed since last commit?", "show me staged files", etc.',
  'aiAssistant.inputPlaceholder': 'Ask about this repo…',
  'aiAssistant.noRepo': 'No repo',
  'aiAssistant.loading': 'Loading…',
  'aiAssistant.noRepoMode': 'No repository (app-level mode)',
  'aiAssistant.emptyHintNoRepo': 'No repository is open. Ask me to list your repos, clone a new one, or initialize a fresh project. Try: "list my repos" or "clone https://github.com/user/repo".',
  'aiAssistant.inputPlaceholderNoRepo': 'Ask me to list, clone, or create a repo…',
  'aiAssistant.thinking': 'Thinking…',
  'aiAssistant.send': 'Send',

  // ── Session switcher ─────────────────────────────────────────────────────
  'aiAssistant.noRepoToolsHint': 'Use list_repos / clone_repo / init_repo tools.',
  'aiAssistant.knownRepositories': 'Known repositories',
  'aiAssistant.noRepositoriesYet': 'No repositories yet. Switch to "No repository" mode and use clone_repo or init_repo.',
  'aiAssistant.currentRepo': 'current',
  'aiAssistant.sessionNoRepo': 'No repository (app-level mode)',

  // ── Message actions ──────────────────────────────────────────────────────
  'aiAssistant.retry': 'Retry',
  'aiAssistant.copy': 'Copy',
  'aiAssistant.copied': 'Copied',
  'aiAssistant.copyMessage': 'Copy message',
  'aiAssistant.copyResult': 'Copy result',
  'aiAssistant.resendMessage': 'Resend this message',
  'aiAssistant.regenerateResponse': 'Regenerate this response',

  // ── Tool result bubble ───────────────────────────────────────────────────
  'aiAssistant.emptyResult': '(empty result)',
  'aiAssistant.line': 'line',
  'aiAssistant.lines': 'lines',

  // ── Token usage bar ──────────────────────────────────────────────────────
  'aiAssistant.tokensInput': 'Input tokens (sent to the model)',
  'aiAssistant.tokensOutput': 'Output tokens (generated by the model)',
  'aiAssistant.tokensContext': 'Total context size (all messages + tools sent to the model)',
  'aiAssistant.tokensIn': 'in',
  'aiAssistant.tokensOut': 'out',
  'aiAssistant.tokensCtx': 'ctx',
  'aiAssistant.largeContextWarn': 'large context',
  'aiAssistant.largeContextTitle': 'Context is getting large — consider starting a new conversation',

  // ── Stop state ───────────────────────────────────────────────────────────
  'aiAssistant.stoppedByUser': '⏹ Stopped by user. The conversation history is preserved — you can continue with a new message.',

  // ── Chat Search panel (AiChatPage) ───────────────────────────────────────
  'aiAssistant.chatSearch': 'Chat Search',
  'aiAssistant.searchPlaceholder': 'Search messages…',
  'aiAssistant.clearSearch': 'Clear search',
  'aiAssistant.searchHintEmpty': 'Type to search through the chat history. Matching messages are filtered in the chat panel on the left, and listed here as quick previews.',
  'aiAssistant.noMatchesFound': 'No matches found.',
  'aiAssistant.noMessagesMatch': 'No messages match “{query}”.',
  'aiAssistant.match': 'match',
  'aiAssistant.matches': 'matches',
  'aiAssistant.total': 'total',
  'aiAssistant.message': 'message',
  'aiAssistant.messages': 'messages',

  // ── Starter prompts ──────────────────────────────────────────────────────
  'aiAssistant.starterWhatChanged': 'What changed?',
  'aiAssistant.starterPullLatest': 'Pull latest',
  'aiAssistant.starterRecentCommits': 'Recent commits',
  'aiAssistant.starterListBranches': 'List branches',
  'aiAssistant.starterStashChanges': 'Stash changes',
  'aiAssistant.starterPushCommits': 'Push commits',
  'aiAssistant.starterListRepos': 'List my repos',
  'aiAssistant.starterCloneRepo': 'Clone a repo',
  'aiAssistant.starterCreateRepo': 'Create a repo',
};

export const ru: Record<string, string> = {
  // ── Header / titles ──────────────────────────────────────────────────────
  'aiAssistant.title': 'AI Ассистент',
  'aiAssistant.toggleTitle': 'Переключить чат AI Ассистента (Ctrl+Shift+A)',
  'aiAssistant.disabledHint': 'Сначала включите AI в Настройки → AI',
  'aiAssistant.clearHistory': 'Очистить историю чата',
  'aiAssistant.clearChat': 'Очистить чат',
  'aiAssistant.exportChatLog': 'Экспортировать лог чата как Markdown (для отладки / обмена)',
  'aiAssistant.exportChatLabel': 'Экспорт лога',
  'aiAssistant.stopGeneration': 'Остановить генерацию',
  'aiAssistant.stopButton': 'Стоп',
  'aiAssistant.switchProvider': 'Сменить AI провайдера',
  'aiAssistant.switchProviderHint': 'Переключение сохраняет разговор — новый провайдер продолжит чат.',
  'aiAssistant.noProviderSelected': 'нет провайдера',
  'aiAssistant.providerTitle': 'Провайдер',

  // ── Empty / loading states ───────────────────────────────────────────────
  'aiAssistant.emptyHint': 'Спросите что угодно об этом репозитории — "что изменилось с последнего коммита?", "покажи staged файлы" и т.д.',
  'aiAssistant.inputPlaceholder': 'Спросите об этом репозитории…',
  'aiAssistant.noRepo': 'Нет репо',
  'aiAssistant.loading': 'Загрузка…',
  'aiAssistant.noRepoMode': 'Без репозитория (режим приложения)',
  'aiAssistant.emptyHintNoRepo': 'Репозиторий не открыт. Попросите меня показать список ваших репо, склонировать новый или инициализировать проект. Например: "покажи мои репо" или "clone https://github.com/user/repo".',
  'aiAssistant.inputPlaceholderNoRepo': 'Попросите показать, склонировать или создать репо…',
  'aiAssistant.thinking': 'Думаю…',
  'aiAssistant.send': 'Отправить',

  // ── Session switcher ─────────────────────────────────────────────────────
  'aiAssistant.noRepoToolsHint': 'Используйте инструменты list_repos / clone_repo / init_repo.',
  'aiAssistant.knownRepositories': 'Известные репозитории',
  'aiAssistant.noRepositoriesYet': 'Пока нет репозиториев. Переключитесь в режим "Без репозитория" и используйте clone_repo или init_repo.',
  'aiAssistant.currentRepo': 'текущий',
  'aiAssistant.sessionNoRepo': 'Без репозитория (режим приложения)',

  // ── Message actions ──────────────────────────────────────────────────────
  'aiAssistant.retry': 'Повторить',
  'aiAssistant.copy': 'Копировать',
  'aiAssistant.copied': 'Скопировано',
  'aiAssistant.copyMessage': 'Копировать сообщение',
  'aiAssistant.copyResult': 'Копировать результат',
  'aiAssistant.resendMessage': 'Отправить это сообщение снова',
  'aiAssistant.regenerateResponse': 'Сгенерировать ответ заново',

  // ── Tool result bubble ───────────────────────────────────────────────────
  'aiAssistant.emptyResult': '(пустой результат)',
  'aiAssistant.line': 'строка',
  'aiAssistant.lines': 'строк',

  // ── Token usage bar ──────────────────────────────────────────────────────
  'aiAssistant.tokensInput': 'Входящие токены (отправлены модели)',
  'aiAssistant.tokensOutput': 'Исходящие токены (сгенерированы моделью)',
  'aiAssistant.tokensContext': 'Общий размер контекста (все сообщения + инструменты, отправленные модели)',
  'aiAssistant.tokensIn': 'вх',
  'aiAssistant.tokensOut': 'исх',
  'aiAssistant.tokensCtx': 'конт',
  'aiAssistant.largeContextWarn': 'большой контекст',
  'aiAssistant.largeContextTitle': 'Контекст становится большим — попробуйте начать новый разговор',

  // ── Stop state ───────────────────────────────────────────────────────────
  'aiAssistant.stoppedByUser': '⏹ Остановлено пользователем. История разговора сохранена — вы можете продолжить новым сообщением.',

  // ── Chat Search panel (AiChatPage) ───────────────────────────────────────
  'aiAssistant.chatSearch': 'Поиск по чату',
  'aiAssistant.searchPlaceholder': 'Поиск сообщений…',
  'aiAssistant.clearSearch': 'Очистить поиск',
  'aiAssistant.searchHintEmpty': 'Введите запрос для поиска по истории чата. Совпадения фильтруются в панели чата слева и отображаются здесь как быстрый предпросмотр.',
  'aiAssistant.noMatchesFound': 'Совпадения не найдены.',
  'aiAssistant.noMessagesMatch': 'Нет сообщений, содержащих “{query}”.',
  'aiAssistant.match': 'совпадение',
  'aiAssistant.matches': 'совпадений',
  'aiAssistant.total': 'всего',
  'aiAssistant.message': 'сообщение',
  'aiAssistant.messages': 'сообщений',

  // ── Starter prompts ──────────────────────────────────────────────────────
  'aiAssistant.starterWhatChanged': 'Что изменилось?',
  'aiAssistant.starterPullLatest': 'Получить последние',
  'aiAssistant.starterRecentCommits': 'Недавние коммиты',
  'aiAssistant.starterListBranches': 'Список веток',
  'aiAssistant.starterStashChanges': 'Спрятать изменения',
  'aiAssistant.starterPushCommits': 'Отправить коммиты',
  'aiAssistant.starterListRepos': 'Мои репозитории',
  'aiAssistant.starterCloneRepo': 'Клонировать репо',
  'aiAssistant.starterCreateRepo': 'Создать репо',
};

export const zh: Record<string, string> = {
  // ── Header / titles ──────────────────────────────────────────────────────
  'aiAssistant.title': 'AI 助手',
  'aiAssistant.toggleTitle': '切换 AI 助手聊天 (Ctrl+Shift+A)',
  'aiAssistant.disabledHint': '请先在 设置 → AI 中启用 AI',
  'aiAssistant.clearHistory': '清除聊天记录',
  'aiAssistant.clearChat': '清空聊天',
  'aiAssistant.exportChatLog': '将聊天日志导出为 Markdown（用于调试 / 分享）',
  'aiAssistant.exportChatLabel': '导出日志',
  'aiAssistant.stopGeneration': '停止生成',
  'aiAssistant.stopButton': '停止',
  'aiAssistant.switchProvider': '切换 AI 提供商',
  'aiAssistant.switchProviderHint': '切换会保留对话 — 新提供商将继续聊天。',
  'aiAssistant.noProviderSelected': '无提供商',
  'aiAssistant.providerTitle': '提供商',

  // ── Empty / loading states ───────────────────────────────────────────────
  'aiAssistant.emptyHint': '问任何关于此仓库的问题 — "自上次提交以来有什么变化？"、"显示暂存文件" 等。',
  'aiAssistant.inputPlaceholder': '询问此仓库…',
  'aiAssistant.noRepo': '无仓库',
  'aiAssistant.loading': '加载中…',
  'aiAssistant.noRepoMode': '无仓库（应用级模式）',
  'aiAssistant.emptyHintNoRepo': '尚未打开任何仓库。让我列出您的仓库、克隆新仓库或初始化新项目。试试："列出我的仓库" 或 "clone https://github.com/user/repo"。',
  'aiAssistant.inputPlaceholderNoRepo': '让我列出、克隆或创建仓库…',
  'aiAssistant.thinking': '思考中…',
  'aiAssistant.send': '发送',

  // ── Session switcher ─────────────────────────────────────────────────────
  'aiAssistant.noRepoToolsHint': '使用 list_repos / clone_repo / init_repo 工具。',
  'aiAssistant.knownRepositories': '已知仓库',
  'aiAssistant.noRepositoriesYet': '尚无仓库。切换到"无仓库"模式，使用 clone_repo 或 init_repo。',
  'aiAssistant.currentRepo': '当前',
  'aiAssistant.sessionNoRepo': '无仓库（应用级模式）',

  // ── Message actions ──────────────────────────────────────────────────────
  'aiAssistant.retry': '重试',
  'aiAssistant.copy': '复制',
  'aiAssistant.copied': '已复制',
  'aiAssistant.copyMessage': '复制消息',
  'aiAssistant.copyResult': '复制结果',
  'aiAssistant.resendMessage': '重新发送此消息',
  'aiAssistant.regenerateResponse': '重新生成此回复',

  // ── Tool result bubble ───────────────────────────────────────────────────
  'aiAssistant.emptyResult': '（空结果）',
  'aiAssistant.line': '行',
  'aiAssistant.lines': '行',

  // ── Token usage bar ──────────────────────────────────────────────────────
  'aiAssistant.tokensInput': '输入令牌（发送给模型）',
  'aiAssistant.tokensOutput': '输出令牌（模型生成）',
  'aiAssistant.tokensContext': '总上下文大小（所有消息 + 工具发送给模型）',
  'aiAssistant.tokensIn': '入',
  'aiAssistant.tokensOut': '出',
  'aiAssistant.tokensCtx': '上下文',
  'aiAssistant.largeContextWarn': '上下文过大',
  'aiAssistant.largeContextTitle': '上下文过大 — 建议开始新的对话',

  // ── Stop state ───────────────────────────────────────────────────────────
  'aiAssistant.stoppedByUser': '⏹ 用户已停止。对话历史已保留 — 您可以继续发送新消息。',

  // ── Chat Search panel (AiChatPage) ───────────────────────────────────────
  'aiAssistant.chatSearch': '聊天搜索',
  'aiAssistant.searchPlaceholder': '搜索消息…',
  'aiAssistant.clearSearch': '清除搜索',
  'aiAssistant.searchHintEmpty': '输入以搜索聊天历史。匹配的消息将在左侧聊天面板中过滤，并在此处作为快速预览列出。',
  'aiAssistant.noMatchesFound': '未找到匹配项。',
  'aiAssistant.noMessagesMatch': '没有消息匹配“{query}”。',
  'aiAssistant.match': '个匹配',
  'aiAssistant.matches': '个匹配',
  'aiAssistant.total': '总数',
  'aiAssistant.message': '条消息',
  'aiAssistant.messages': '条消息',

  // ── Starter prompts ──────────────────────────────────────────────────────
  'aiAssistant.starterWhatChanged': '有什么变化？',
  'aiAssistant.starterPullLatest': '拉取最新',
  'aiAssistant.starterRecentCommits': '最近提交',
  'aiAssistant.starterListBranches': '列出分支',
  'aiAssistant.starterStashChanges': '暂存更改',
  'aiAssistant.starterPushCommits': '推送提交',
  'aiAssistant.starterListRepos': '我的仓库',
  'aiAssistant.starterCloneRepo': '克隆仓库',
  'aiAssistant.starterCreateRepo': '创建仓库',
};

export const de: Record<string, string> = {
  // ── Header / titles ──────────────────────────────────────────────────────
  'aiAssistant.title': 'KI-Assistent',
  'aiAssistant.toggleTitle': 'KI-Assistent-Chat umschalten (Strg+Shift+A)',
  'aiAssistant.disabledHint': 'Aktivieren Sie KI in Einstellungen → KI',
  'aiAssistant.clearHistory': 'Chat-Verlauf löschen',
  'aiAssistant.clearChat': 'Chat löschen',
  'aiAssistant.exportChatLog': 'Chat-Verlauf als Markdown exportieren (für Debugging / Freigabe)',
  'aiAssistant.exportChatLabel': 'Protokoll exportieren',
  'aiAssistant.stopGeneration': 'Generierung stoppen',
  'aiAssistant.stopButton': 'Stopp',
  'aiAssistant.switchProvider': 'KI-Anbieter wechseln',
  'aiAssistant.switchProviderHint': 'Wechseln erhält die Konversation — der neue Anbieter setzt den Chat fort.',
  'aiAssistant.noProviderSelected': 'kein Anbieter',
  'aiAssistant.providerTitle': 'Anbieter',

  // ── Empty / loading states ───────────────────────────────────────────────
  'aiAssistant.emptyHint': 'Fragen Sie alles über dieses Repository — "was hat sich seit dem letzten Commit geändert?", "zeige mir gestaffte Dateien" usw.',
  'aiAssistant.inputPlaceholder': 'Fragen Sie zu diesem Repo…',
  'aiAssistant.noRepo': 'Kein Repo',
  'aiAssistant.loading': 'Laden…',
  'aiAssistant.noRepoMode': 'Kein Repository (App-Ebene-Modus)',
  'aiAssistant.emptyHintNoRepo': 'Kein Repository geöffnet. Bitten Sie mich, Ihre Repos aufzulisten, ein neues zu klonen oder ein Projekt zu initialisieren. Versuchen Sie: "meine Repos auflisten" oder "clone https://github.com/user/repo".',
  'aiAssistant.inputPlaceholderNoRepo': 'Bitten Sie mich, Repos aufzulisten, zu klonen oder zu erstellen…',
  'aiAssistant.thinking': 'Denke nach…',
  'aiAssistant.send': 'Senden',

  // ── Session switcher ─────────────────────────────────────────────────────
  'aiAssistant.noRepoToolsHint': 'Verwenden Sie list_repos / clone_repo / init_repo Werkzeuge.',
  'aiAssistant.knownRepositories': 'Bekannte Repositories',
  'aiAssistant.noRepositoriesYet': 'Noch keine Repositories. Wechseln Sie in den Modus "Kein Repository" und verwenden Sie clone_repo oder init_repo.',
  'aiAssistant.currentRepo': 'aktuell',
  'aiAssistant.sessionNoRepo': 'Kein Repository (App-Ebene-Modus)',

  // ── Message actions ──────────────────────────────────────────────────────
  'aiAssistant.retry': 'Erneut',
  'aiAssistant.copy': 'Kopieren',
  'aiAssistant.copied': 'Kopiert',
  'aiAssistant.copyMessage': 'Nachricht kopieren',
  'aiAssistant.copyResult': 'Ergebnis kopieren',
  'aiAssistant.resendMessage': 'Diese Nachricht erneut senden',
  'aiAssistant.regenerateResponse': 'Diese Antwort neu generieren',

  // ── Tool result bubble ───────────────────────────────────────────────────
  'aiAssistant.emptyResult': '(leeres Ergebnis)',
  'aiAssistant.line': 'Zeile',
  'aiAssistant.lines': 'Zeilen',

  // ── Token usage bar ──────────────────────────────────────────────────────
  'aiAssistant.tokensInput': 'Eingabe-Token (an das Modell gesendet)',
  'aiAssistant.tokensOutput': 'Ausgabe-Token (vom Modell generiert)',
  'aiAssistant.tokensContext': 'Gesamte Kontextgröße (alle Nachrichten + Werkzeuge an das Modell gesendet)',
  'aiAssistant.tokensIn': 'ein',
  'aiAssistant.tokensOut': 'aus',
  'aiAssistant.tokensCtx': 'Ktx',
  'aiAssistant.largeContextWarn': 'großer Kontext',
  'aiAssistant.largeContextTitle': 'Kontext wird groß — erwägen Sie, eine neue Konversation zu beginnen',

  // ── Stop state ───────────────────────────────────────────────────────────
  'aiAssistant.stoppedByUser': '⏹ Vom Benutzer gestoppt. Der Konversationsverlauf bleibt erhalten — Sie können mit einer neuen Nachricht fortfahren.',

  // ── Chat Search panel (AiChatPage) ───────────────────────────────────────
  'aiAssistant.chatSearch': 'Chat-Suche',
  'aiAssistant.searchPlaceholder': 'Nachrichten durchsuchen…',
  'aiAssistant.clearSearch': 'Suche löschen',
  'aiAssistant.searchHintEmpty': 'Tippen Sie, um den Chat-Verlauf zu durchsuchen. Übereinstimmende Nachrichten werden im Chat-Panel links gefiltert und hier als schnelle Vorschau aufgelistet.',
  'aiAssistant.noMatchesFound': 'Keine Treffer gefunden.',
  'aiAssistant.noMessagesMatch': 'Keine Nachrichten entsprechen „{query}“.',
  'aiAssistant.match': 'Treffer',
  'aiAssistant.matches': 'Treffer',
  'aiAssistant.total': 'gesamt',
  'aiAssistant.message': 'Nachricht',
  'aiAssistant.messages': 'Nachrichten',

  // ── Starter prompts ──────────────────────────────────────────────────────
  'aiAssistant.starterWhatChanged': 'Was hat sich geändert?',
  'aiAssistant.starterPullLatest': 'Neueste abrufen',
  'aiAssistant.starterRecentCommits': 'Letzte Commits',
  'aiAssistant.starterListBranches': 'Branches auflisten',
  'aiAssistant.starterStashChanges': 'Änderungen stashen',
  'aiAssistant.starterPushCommits': 'Commits pushen',
  'aiAssistant.starterListRepos': 'Meine Repos',
  'aiAssistant.starterCloneRepo': 'Repo klonen',
  'aiAssistant.starterCreateRepo': 'Repo erstellen',
};
