/**
 * Unit tests for application icon assets (build/) and the electron-builder
 * icon wiring in package.json.
 *
 * The icons are generated by scripts/make-icons.py and committed to the repo;
 * these tests make sure the artifacts are present, valid (PNG/ICO/ICNS
 * headers parsed by hand — no binary deps needed) and correctly referenced
 * from the electron-builder config, so `npm run package:*` always produces
 * a branded bundle instead of the default Electron icon.
 */
import { describe, it, expect } from 'vitest';
import { readFileSync, existsSync } from 'fs';
import { resolve } from 'path';

// vitest always runs from the project root
const ROOT = resolve(process.cwd());

function pngSize(p: string): { width: number; height: number } {
  const buf = readFileSync(p);
  // PNG magic (8 bytes) + IHDR length/type (8 bytes) + width/height (8 bytes)
  expect(buf.subarray(0, 8).equals(Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a])), `${p} is not a PNG`).toBe(true);
  expect(buf.subarray(12, 16).toString('ascii')).toBe('IHDR');
  return { width: buf.readUInt32BE(16), height: buf.readUInt32BE(20) };
}

describe('icon assets (build/)', () => {
  it('master icon.png is a 1024x1024 PNG', () => {
    expect(pngSize(`${ROOT}/build/icon.png`)).toEqual({ width: 1024, height: 1024 });
  });

  it('icon-512.png (window icon) is 512x512', () => {
    expect(pngSize(`${ROOT}/build/icon-512.png`)).toEqual({ width: 512, height: 512 });
  });

  it('logo-256.png (About window) is 256x256', () => {
    expect(pngSize(`${ROOT}/build/logo-256.png`)).toEqual({ width: 256, height: 256 });
  });

  it('linux icon set build/icons/ contains all required sizes', () => {
    for (const size of [16, 24, 32, 48, 64, 96, 128, 256, 512]) {
      const p = `${ROOT}/build/icons/${size}x${size}.png`;
      expect(existsSync(p), `${p} missing`).toBe(true);
      expect(pngSize(p)).toEqual({ width: size, height: size });
    }
  });

  it('icon.ico has a valid ICO header with all size entries', () => {
    const buf = readFileSync(`${ROOT}/build/icon.ico`);
    // reserved=0, type=1 (icon), count=N
    expect(buf.readUInt16LE(0)).toBe(0);
    expect(buf.readUInt16LE(2)).toBe(1);
    const count = buf.readUInt16LE(4);
    expect(count).toBe(7); // 16,24,32,48,64,128,256
    const expected = new Set([16, 24, 32, 48, 64, 128, 256]);
    const seen = new Set<number>();
    for (let i = 0; i < count; i++) {
      const off = 6 + i * 16;
      const w = buf[off] === 0 ? 256 : buf[off]; // 0 means 256
      const h = buf[off + 1] === 0 ? 256 : buf[off + 1];
      const bytes = buf.readUInt32LE(off + 8);
      expect(h).toBe(w);
      expect(bytes).toBeGreaterThan(0);
      seen.add(w);
    }
    expect(seen).toEqual(expected);
  });

  it('icon.icns has a valid ICNS header with matching total length', () => {
    const buf = readFileSync(`${ROOT}/build/icon.icns`);
    expect(buf.subarray(0, 4).toString('ascii')).toBe('icns');
    const total = buf.readUInt32BE(4);
    expect(total).toBe(buf.length);
    // must embed the large PNG-based chunk types
    const ascii = buf.subarray(8).toString('latin1');
    for (const type of ['ic07', 'ic08', 'ic09', 'ic10']) {
      expect(ascii.includes(type), `missing ${type} chunk`).toBe(true);
    }
  });
});

describe('electron-builder icon wiring (package.json build config)', () => {
  const pkg = JSON.parse(readFileSync(`${ROOT}/package.json`, 'utf8'));

  it('mac target uses build/icon.icns', () => {
    expect(pkg.build.mac.icon).toBe('build/icon.icns');
  });

  it('win target uses build/icon.ico', () => {
    expect(pkg.build.win.icon).toBe('build/icon.ico');
  });

  it('linux target uses the build/icons directory', () => {
    expect(pkg.build.linux.icon).toBe('build/icons');
  });

  it('extraResources ships icon-512.png and logo-256.png for runtime windows', () => {
    const tos = pkg.build.extraResources.map((e: { to: string }) => e.to);
    expect(tos).toContain('icon-512.png');
    expect(tos).toContain('logo-256.png');
  });

  it('an "icons" npm script regenerates the assets', () => {
    expect(pkg.scripts.icons).toBe('python3 scripts/make-icons.py');
  });
});
